### ISSUE TITLE
Extended input checks

### ISSUE THREAD

**Issue by tnagler** [JonasMoss/univariateML#28]
These should probably throw an error:
``` r
> mat_3cols <- replicate(3, rexp(100))
> mlexp(mat_3cols)
Maximum likelihood estimates for the Exponential model 
rate  
1.07
```  
``` r
> mlexp(letters[1:5])
Maximum likelihood estimates for the Exponential model 
rate  
  NA  
Warning message:
In mean.default(x) : argument is not numeric or logical: returning NA
```

**Comment by JonasMoss** [comment]
I'll make an input checker that is called at the start of each `ml***` function and check for numeric vectors. (And probably let it handle `na` and `support` too.)

@tnagler do you know how cases such `replicate(3, rexp(100))` is usually handled? I guess checking for a `NULL` dim attribute is the way to go...

**Comment by tnagler** [comment]
I think I usually do `NCOL(x) == 1` and `is.numeric(x)`

**Comment by JonasMoss** [comment]
c4aa81c
