### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by tnagler** [JonasMoss/univariateML#37]
Would it be possible to make publish a new CRAN version in the next 1-2 weeks? (I want to publish a new package which relies on univariateML). I can help preparing everything if necessary.

**Comment by JonasMoss** [comment]
Absolutely no problem! =)

Is there anything more you'd like to add before the release except the vignette pull-request? If not, I can make a new CRAN release tomorrow.

**Comment by tnagler** [comment]
That's it for now! I still have the discrete families on my list, but that's for another time ;)

**Comment by JonasMoss** [comment]
Alright, on its way to cran now =)

**Comment by tnagler** [comment]
Great, thanks!
