### ISSUE TITLE
Attributes on the ml*** functions.

### ISSUE THREAD

**Issue by JonasMoss** [JonasMoss/univariateML#39]
Sometimes we need to know e.g. the support of the `ml***` before calling it. For instance, the package `kdensity` needs both the support and the name of the density. Or by finding the "attr(object, "support")" part of the code.

One way to fix this is to let the functions themselves have attributes.

**Comment by tripartio** [comment]
I agree. This would be very useful. Here's my proposed solution. 

First, define an internal function that sets the attributes of an `ml***` function. It does so by creating a dummy `univariateML` object and then copying the relevant attributes. My code here doesn't use `roxygen`, but the documentation should explain what's going on:

```
set_ml_fun_attr <- function(
    ml_fun,  # the literal function (not a character string, e.g., mlnorm, mlpois, etc.)
    x = 1    # a dummy vector to use to create a temporary univariateML object
  ) {
  # Create a temporary univariateML object so that we can get the standard object
  # attributes for this ml* object type.
  ml_obj_attr <- ml_fun(x)
  
  # Copy the attributes that are relevant not just to an object but to the function itself
  attr(ml_fun, "params") <- attr(ml_obj_attr, "names")
  attr(ml_fun, "model") <- attr(ml_obj_attr, "model")
  attr(ml_fun, "density") <- attr(ml_obj_attr, "density")
  attr(ml_fun, "support") <- attr(ml_obj_attr, "support")
  
  ml_fun
}
```

This function could go in `utility.R` or `helpers.R` or wherever you feel suitable for this kind of thing.

Next, in each `ml***.R` file right after the `ml***` function definition, call `set_ml_fun_attr()` to add attributes to the `ml***` function itself. For example, for `mlnorm.R`, we would have:

```r
mlnorm <- function(...) {
  # function code
}

mlnorm <- set_ml_fun_attr(mlnorm)
```

<sup>Created on 2024-09-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
```
With my very basic testing, I think that resolves this issue. We can verify the attributes with
```r
attributes(mlnorm)
#> $params
#> [1] "mean" "sd"  
#> 
#> $model
#> [1] "Normal"
#> 
#> $density
#> [1] "stats::dnorm"
#> 
#> $support
#> [1] -Inf  Inf
```

What do you think?

**Comment by tripartio** [comment]
An alternative approach would be to put `set_ml_fun_attr()` in the `zzz.R` file (that runs after all other files have run) and then automatically update all `ml***` functions with the attributes. The advantage of this approach is that there would be no need to modify the individual `ml***.R` files. Something like this is my initial idea:

```r
# densities is the character vector of ml*** function names from densities.R
for (ml_fun in densities) {
  assign(
    ml_fun,
    set_ml_fun_attr(get(ml_fun))  # get() needed because ml_fun here is a string
  )
}
```

The problem with this, though, is that some `ml***()` functions choke on the default `set_ml_fun_attr(get(ml_fun), x = 1)`. For example, `mlbeta()` requires `x` values to be less than 1. So, my first idea of calling something like `ml*** <- set_ml_fun_attr(ml***)` in each `ml***.R` file might be needed to ensure that each model's assumptions are attended to.

**Comment by JonasMoss** [comment]
Good idea! But it just *almost* works, as some distributions (pareto and uniform) have supports that depend on the data. It's possible to hack ourselves around that, but that's not elegant. Instead, I've started to refactor the code pretty seriously now. Branch for this here: https://github.com/JonasMoss/univariateML/tree/attributes-decorator 

* Most of the code in `ml***` functions are boilerplate that can be constructed  using decorators. (Just as you suggested.) 
* The information can be stored in a separate `metadata` list, or potentially as attributes on the functions. See https://github.com/JonasMoss/univariateML/tree/attributes-decorator for an example. 
* Using the `intervals` package to handle supports. This lets us specify float or integer intervals with open or closed endpoints. It's possible to handle parameter-dependent supports by adding names to the intervals. (Not done yet.)

The code works, but only implemented for `mlexp`, `mlnaka` and `mlexp` as of now.

**Comment by tripartio** [comment]
I'm sure you have a vision that is guiding your refactoring of the code, so I have no comments on that.

But on the present issue, if only a few distributions (like pareto and uniform) have supports that depend on the data, then it should be simple to resolve that by setting the `mlpareto` support attribute to `NULL`. Wouldn't that resolve the issue?

**Comment by JonasMoss** [comment]
This is implemented in https://github.com/JonasMoss/univariateML/tree/attributes-decorator (decorator in helpers.R) using a similar solution as @tripartio  described.
