### ISSUE TITLE
bug in model_select

### ISSUE THREAD

**Issue by oezgesahin** [JonasMoss/univariateML#45]
Hello, 
It seems that the [fix](https://github.com/JonasMoss/univariateML/commit/0fb3cce2e5ff58273e53c34207f091a668024bcc) resulted in a bug in [model_select](https://github.com/JonasMoss/univariateML/blob/master/R/model_select.R) function. 
For all available distributions:
```
set.seed(1)
x <- actuar::rllogis(500, shape = 3, rate = 2)
univariateML::model_select(x, criterion = "bic")
Error in log(nos) : non-numeric argument to mathematical function
```
For normal distribution:
```
univariateML::model_select(x, models = "norm", criterion = "bic")
Maximum likelihood estimates for the Normal model 
  mean      sd  
0.5834  0.3815 
```
For log-logistic distribution:
```
univariateML::model_select(x, models = "llogis", criterion = "bic")
Error in log(nos) : non-numeric argument to mathematical function
```
I cannot easily see why it happens.

**Comment by JonasMoss** [comment]
Thanks, I somehow removed `n` when fixing mlllogis, https://github.com/JonasMoss/univariateML/commit/ed2a8ff1298f30270c73a750366a7c874071ecd7.
