### ISSUE TITLE
installation from GitHub 

### ISSUE THREAD

**Issue by oezgesahin** [JonasMoss/univariateML#47]
Hello, 
when I tried to install the development version of the package, I got a warning for the `actuar` package:
```
> devtools::install_github("JonasMoss/univariateML")
Downloading GitHub repo JonasMoss/univariateML@HEAD
Skipping 1 packages not available: actuar
```
It seems to result from the actuar's R dependence (≥ 4.1.0) in [its last version](https://cran.r-project.org/web/packages/actuar/index.html). 
Is there a way to solve this issue besides updating the R version or installing the package via CRAN?

**Comment by JonasMoss** [comment]
I don't think there's an easy way to go around. I just noticed this problem myself when running CRAN R CMD checks on `oldrel-1`.  It's possible to modify the package to merely suggest `actuar`, but that would be quite a hassle not worth it, IMO.

**Comment by oezgesahin** [comment]
True. Thanks then.
